jobs:
  build:
    docker:
      - image: 'circleci/node:current'
    steps:
      - checkout
      - run: echo "npm installing"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - setup_remote_docker:
          docker_layer_caching: true    
      - run: yarn ci:docker
  test:
    docker:
      - image: 'circleci/node:current'
    steps:
      - checkout
      - run: echo "run testing"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn test
version: 2.1
workflows:
  build_test_lint:
    jobs:
      - test
      - build:
          requires:
            - test
  version: 2.1
