--- 
  jobs: 
    lint: 
      docker: 
        - 
          image: "circleci/node:current"
      steps: 
        - checkout
        - 
          run: "echo \"run linting\""
        - 
          run: "npm test"    
    build: 
      docker: 
        - 
          image: "circleci/node:current"
      steps: 
        - checkout
        - 
          run: "echo \"npm installing\""
        - 
          run: "npm install"
        - 
          run: "npm build"          
    test: 
      docker: 
        - 
          image: "circleci/node:current"
      steps: 
        - checkout
        - 
          run: "echo \"run testing\""
        - 
          run: "npm install"
        - 
          run: "npm test"
  version: 2.1
  workflows: 
    build_test_lint: 
      jobs: 
        - lint
        - build
        - test
    version: 2.1
  