--- 
  jobs: 
    build: 
      docker: 
        - 
          image: "circleci/node:12.9.1-browsers"
      working_directory: ~/repo
  steps: 
    - checkout
    - 
      keys: 
        - "v1-dependencies-{{ checksum \"package.json\" }}"
        - v1-dependencies-
      restore_cache: ~
    - 
      run: "yarn install"
    - 
      key: "v1-dependencies-{{ checksum \"package.json\" }}"
      paths: 
        - node_modules
        - ~/.npm
        - ~/.cache
      save_cache: ~
    - 
      run: "yarn lint"
    - 
      run: "yarn test"
  version: 2.1
  