orbs:
  cypress: cypress-io/cypress@1.26.0
jobs:
  build:
    docker:
      - image: 'circleci/node:current'
    steps:
      - checkout
      - run: echo "npm installing"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    docker:
      - image: 'circleci/node:current'
    steps:
      - checkout
      - run: echo "run testing"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn test
version: 2.1
workflows:
  build_test_lint:
    jobs:
      - cypress/install:
          pre-steps:
            - checkout
      - cypress/run:    
          requires:
            - cypress/install
          install-command: 'yarn install --frozen-lockfile'
          verify-command: yarn cypress verify
          command: yarn e2e
      - test
      - build:
          requires:
            - test

