orbs:
  cypress: cypress-io/cypress@1.26.0
jobs:
  build:
    docker:
      - image: 'circleci/node:current'
    steps:
      - checkout
      - run: echo "npm installing"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    docker:
      - image: 'circleci/node:current'
    steps:
      - checkout
      - run: echo "run testing"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn test
version: 2.1
workflows:
  build_test_lint:
    jobs:
      - test
      - build:
          requires:
            - test      
      - cypress/install:
          pre-steps:
            - checkout
            - run: yarn install
      - cypress/run:
          yarn: true
          install-command: 'yarn install'
          start: yarn start
          wait-on: 'http://localhost:8000'
          post-steps:
            - run: 'yarn cypress open'